# Generated by Django 3.0.2 on 2020-08-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('level', models.IntegerField(choices=[(0, 'Not Set'), (20, 'Info'), (30, 'Warning'), (10, 'Debug'), (40, 'Error'), (50, 'Fatal')], db_index=True, default=40)),
                ('subject', models.CharField(max_length=200)),
                ('logger_name', models.CharField(max_length=100)),
                ('path_name', models.CharField(max_length=200)),
                ('func_name', models.CharField(max_length=100)),
                ('line_num', models.IntegerField()),
                ('traceback', models.TextField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
